/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.IimmpactApi) {
      root.IimmpactApi = {};
    }
    root.IimmpactApi.BalanceStatementResponseMeta = factory(root.IimmpactApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The BalanceStatementResponseMeta model module.
   * @module model/BalanceStatementResponseMeta
   * @version 2020-09-14T13:01:14Z
   */

  /**
   * Constructs a new <code>BalanceStatementResponseMeta</code>.
   * @alias module:model/BalanceStatementResponseMeta
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>BalanceStatementResponseMeta</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BalanceStatementResponseMeta} obj Optional instance to populate.
   * @return {module:model/BalanceStatementResponseMeta} The populated <code>BalanceStatementResponseMeta</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('current_page'))
        obj.currentPage = ApiClient.convertToType(data['current_page'], 'Number');
      if (data.hasOwnProperty('from'))
        obj.from = ApiClient.convertToType(data['from'], 'Number');
      if (data.hasOwnProperty('last_page'))
        obj.lastPage = ApiClient.convertToType(data['last_page'], 'Number');
      if (data.hasOwnProperty('path'))
        obj.path = ApiClient.convertToType(data['path'], 'String');
      if (data.hasOwnProperty('per_page'))
        obj.perPage = ApiClient.convertToType(data['per_page'], 'Number');
      if (data.hasOwnProperty('to'))
        obj.to = ApiClient.convertToType(data['to'], 'Number');
      if (data.hasOwnProperty('total'))
        obj.total = ApiClient.convertToType(data['total'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} currentPage
   */
  exports.prototype.currentPage = undefined;

  /**
   * @member {Number} from
   */
  exports.prototype.from = undefined;

  /**
   * @member {Number} lastPage
   */
  exports.prototype.lastPage = undefined;

  /**
   * @member {String} path
   */
  exports.prototype.path = undefined;

  /**
   * @member {Number} perPage
   */
  exports.prototype.perPage = undefined;

  /**
   * @member {Number} to
   */
  exports.prototype.to = undefined;

  /**
   * @member {Number} total
   */
  exports.prototype.total = undefined;

  return exports;

}));
