/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BalanceStatementResponseData', 'model/BalanceStatementResponseLinks', 'model/BalanceStatementResponseMeta'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BalanceStatementResponseData'), require('./BalanceStatementResponseLinks'), require('./BalanceStatementResponseMeta'));
  } else {
    // Browser globals (root is window)
    if (!root.IimmpactApi) {
      root.IimmpactApi = {};
    }
    root.IimmpactApi.BalanceStatementResponse = factory(root.IimmpactApi.ApiClient, root.IimmpactApi.BalanceStatementResponseData, root.IimmpactApi.BalanceStatementResponseLinks, root.IimmpactApi.BalanceStatementResponseMeta);
  }
}(this, function(ApiClient, BalanceStatementResponseData, BalanceStatementResponseLinks, BalanceStatementResponseMeta) {
  'use strict';

  /**
   * The BalanceStatementResponse model module.
   * @module model/BalanceStatementResponse
   * @version 2020-09-14T13:01:14Z
   */

  /**
   * Constructs a new <code>BalanceStatementResponse</code>.
   * @alias module:model/BalanceStatementResponse
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>BalanceStatementResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BalanceStatementResponse} obj Optional instance to populate.
   * @return {module:model/BalanceStatementResponse} The populated <code>BalanceStatementResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], [BalanceStatementResponseData]);
      if (data.hasOwnProperty('links'))
        obj.links = BalanceStatementResponseLinks.constructFromObject(data['links']);
      if (data.hasOwnProperty('meta'))
        obj.meta = BalanceStatementResponseMeta.constructFromObject(data['meta']);
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/BalanceStatementResponseData>} data
   */
  exports.prototype.data = undefined;

  /**
   * @member {module:model/BalanceStatementResponseLinks} links
   */
  exports.prototype.links = undefined;

  /**
   * @member {module:model/BalanceStatementResponseMeta} meta
   */
  exports.prototype.meta = undefined;

  return exports;

}));
