/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.IimmpactApi) {
      root.IimmpactApi = {};
    }
    root.IimmpactApi.BillPresentmentResponseData = factory(root.IimmpactApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The BillPresentmentResponseData model module.
   * @module model/BillPresentmentResponseData
   * @version 2020-09-14T13:01:14Z
   */

  /**
   * Constructs a new <code>BillPresentmentResponseData</code>.
   * @alias module:model/BillPresentmentResponseData
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>BillPresentmentResponseData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BillPresentmentResponseData} obj Optional instance to populate.
   * @return {module:model/BillPresentmentResponseData} The populated <code>BillPresentmentResponseData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('CustomField'))
        obj.customField = ApiClient.convertToType(data['CustomField'], 'String');
      if (data.hasOwnProperty('CustomerName'))
        obj.customerName = ApiClient.convertToType(data['CustomerName'], 'String');
      if (data.hasOwnProperty('Outstanding'))
        obj.outstanding = ApiClient.convertToType(data['Outstanding'], 'Number');
      if (data.hasOwnProperty('Balance'))
        obj.balance = ApiClient.convertToType(data['Balance'], 'String');
      if (data.hasOwnProperty('Data'))
        obj.data = ApiClient.convertToType(data['Data'], 'String');
      if (data.hasOwnProperty('Address'))
        obj.address = ApiClient.convertToType(data['Address'], 'String');
      if (data.hasOwnProperty('E-Bill'))
        obj.eBill = ApiClient.convertToType(data['E-Bill'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} message
   */
  exports.prototype.message = undefined;

  /**
   * @member {String} customField
   */
  exports.prototype.customField = undefined;

  /**
   * @member {String} customerName
   */
  exports.prototype.customerName = undefined;

  /**
   * @member {Number} outstanding
   */
  exports.prototype.outstanding = undefined;

  /**
   * @member {String} balance
   */
  exports.prototype.balance = undefined;

  /**
   * @member {String} data
   */
  exports.prototype.data = undefined;

  /**
   * @member {String} address
   */
  exports.prototype.address = undefined;

  /**
   * @member {String} eBill
   */
  exports.prototype.eBill = undefined;

  return exports;

}));
