/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.IimmpactApi) {
      root.IimmpactApi = {};
    }
    root.IimmpactApi.BillPresentmentResponseMetadata = factory(root.IimmpactApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The BillPresentmentResponseMetadata model module.
   * @module model/BillPresentmentResponseMetadata
   * @version 2020-09-14T13:01:14Z
   */

  /**
   * Constructs a new <code>BillPresentmentResponseMetadata</code>.
   * @alias module:model/BillPresentmentResponseMetadata
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>BillPresentmentResponseMetadata</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BillPresentmentResponseMetadata} obj Optional instance to populate.
   * @return {module:model/BillPresentmentResponseMetadata} The populated <code>BillPresentmentResponseMetadata</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('status_code'))
        obj.statusCode = ApiClient.convertToType(data['status_code'], 'Number');
      if (data.hasOwnProperty('product_code'))
        obj.productCode = ApiClient.convertToType(data['product_code'], 'String');
      if (data.hasOwnProperty('last_updated'))
        obj.lastUpdated = ApiClient.convertToType(data['last_updated'], 'String');
    }
    return obj;
  }

  /**
   * @member {Number} statusCode
   */
  exports.prototype.statusCode = undefined;

  /**
   * @member {String} productCode
   */
  exports.prototype.productCode = undefined;

  /**
   * @member {String} lastUpdated
   */
  exports.prototype.lastUpdated = undefined;

  return exports;

}));
