/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BillPresentmentResponseData', 'model/BillPresentmentResponseMetadata'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BillPresentmentResponseData'), require('./BillPresentmentResponseMetadata'));
  } else {
    // Browser globals (root is window)
    if (!root.IimmpactApi) {
      root.IimmpactApi = {};
    }
    root.IimmpactApi.BillPresentmentResponse = factory(root.IimmpactApi.ApiClient, root.IimmpactApi.BillPresentmentResponseData, root.IimmpactApi.BillPresentmentResponseMetadata);
  }
}(this, function(ApiClient, BillPresentmentResponseData, BillPresentmentResponseMetadata) {
  'use strict';

  /**
   * The BillPresentmentResponse model module.
   * @module model/BillPresentmentResponse
   * @version 2020-09-14T13:01:14Z
   */

  /**
   * Constructs a new <code>BillPresentmentResponse</code>.
   * @alias module:model/BillPresentmentResponse
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>BillPresentmentResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BillPresentmentResponse} obj Optional instance to populate.
   * @return {module:model/BillPresentmentResponse} The populated <code>BillPresentmentResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('data'))
        obj.data = BillPresentmentResponseData.constructFromObject(data['data']);
      if (data.hasOwnProperty('metadata'))
        obj.metadata = BillPresentmentResponseMetadata.constructFromObject(data['metadata']);
    }
    return obj;
  }

  /**
   * @member {module:model/BillPresentmentResponseData} data
   */
  exports.prototype.data = undefined;

  /**
   * @member {module:model/BillPresentmentResponseMetadata} metadata
   */
  exports.prototype.metadata = undefined;

  return exports;

}));
