/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.IimmpactApi) {
      root.IimmpactApi = {};
    }
    root.IimmpactApi.CarInsuranceResponeVariant = factory(root.IimmpactApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The CarInsuranceResponeVariant model module.
   * @module model/CarInsuranceResponeVariant
   * @version 2020-09-14T13:01:14Z
   */

  /**
   * Constructs a new <code>CarInsuranceResponeVariant</code>.
   * @alias module:model/CarInsuranceResponeVariant
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>CarInsuranceResponeVariant</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CarInsuranceResponeVariant} obj Optional instance to populate.
   * @return {module:model/CarInsuranceResponeVariant} The populated <code>CarInsuranceResponeVariant</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('nvic'))
        obj.nvic = ApiClient.convertToType(data['nvic'], 'String');
      if (data.hasOwnProperty('desc'))
        obj.desc = ApiClient.convertToType(data['desc'], 'String');
      if (data.hasOwnProperty('marketValue'))
        obj.marketValue = ApiClient.convertToType(data['marketValue'], 'String');
      if (data.hasOwnProperty('cc'))
        obj.cc = ApiClient.convertToType(data['cc'], 'String');
      if (data.hasOwnProperty('fullmodelDesc'))
        obj.fullmodelDesc = ApiClient.convertToType(data['fullmodelDesc'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} nvic
   */
  exports.prototype.nvic = undefined;

  /**
   * @member {String} desc
   */
  exports.prototype.desc = undefined;

  /**
   * @member {String} marketValue
   */
  exports.prototype.marketValue = undefined;

  /**
   * @member {String} cc
   */
  exports.prototype.cc = undefined;

  /**
   * @member {String} fullmodelDesc
   */
  exports.prototype.fullmodelDesc = undefined;

  return exports;

}));
