/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CarInsuranceResponeVariant'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CarInsuranceResponeVariant'));
  } else {
    // Browser globals (root is window)
    if (!root.IimmpactApi) {
      root.IimmpactApi = {};
    }
    root.IimmpactApi.CarInsuranceRespone = factory(root.IimmpactApi.ApiClient, root.IimmpactApi.CarInsuranceResponeVariant);
  }
}(this, function(ApiClient, CarInsuranceResponeVariant) {
  'use strict';

  /**
   * The CarInsuranceRespone model module.
   * @module model/CarInsuranceRespone
   * @version 2020-09-14T13:01:14Z
   */

  /**
   * Constructs a new <code>CarInsuranceRespone</code>.
   * @alias module:model/CarInsuranceRespone
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>CarInsuranceRespone</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CarInsuranceRespone} obj Optional instance to populate.
   * @return {module:model/CarInsuranceRespone} The populated <code>CarInsuranceRespone</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('make'))
        obj.make = ApiClient.convertToType(data['make'], 'String');
      if (data.hasOwnProperty('model'))
        obj.model = ApiClient.convertToType(data['model'], 'String');
      if (data.hasOwnProperty('yearMake'))
        obj.yearMake = ApiClient.convertToType(data['yearMake'], 'String');
      if (data.hasOwnProperty('chassisNo'))
        obj.chassisNo = ApiClient.convertToType(data['chassisNo'], 'String');
      if (data.hasOwnProperty('engineNo'))
        obj.engineNo = ApiClient.convertToType(data['engineNo'], 'String');
      if (data.hasOwnProperty('seatingCapacity'))
        obj.seatingCapacity = ApiClient.convertToType(data['seatingCapacity'], 'String');
      if (data.hasOwnProperty('variant'))
        obj.variant = ApiClient.convertToType(data['variant'], [CarInsuranceResponeVariant]);
      if (data.hasOwnProperty('vehImage'))
        obj.vehImage = ApiClient.convertToType(data['vehImage'], 'String');
      if (data.hasOwnProperty('nextNCDPerCentage'))
        obj.nextNCDPerCentage = ApiClient.convertToType(data['nextNCDPerCentage'], 'String');
      if (data.hasOwnProperty('nextNcdExpDate'))
        obj.nextNcdExpDate = ApiClient.convertToType(data['nextNcdExpDate'], 'String');
      if (data.hasOwnProperty('currentPolicy'))
        obj.currentPolicy = ApiClient.convertToType(data['currentPolicy'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} message
   */
  exports.prototype.message = undefined;

  /**
   * @member {String} make
   */
  exports.prototype.make = undefined;

  /**
   * @member {String} model
   */
  exports.prototype.model = undefined;

  /**
   * @member {String} yearMake
   */
  exports.prototype.yearMake = undefined;

  /**
   * @member {String} chassisNo
   */
  exports.prototype.chassisNo = undefined;

  /**
   * @member {String} engineNo
   */
  exports.prototype.engineNo = undefined;

  /**
   * @member {String} seatingCapacity
   */
  exports.prototype.seatingCapacity = undefined;

  /**
   * @member {Array.<module:model/CarInsuranceResponeVariant>} variant
   */
  exports.prototype.variant = undefined;

  /**
   * @member {String} vehImage
   */
  exports.prototype.vehImage = undefined;

  /**
   * @member {String} nextNCDPerCentage
   */
  exports.prototype.nextNCDPerCentage = undefined;

  /**
   * @member {String} nextNcdExpDate
   */
  exports.prototype.nextNcdExpDate = undefined;

  /**
   * @member {String} currentPolicy
   */
  exports.prototype.currentPolicy = undefined;

  return exports;

}));
