/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DrivingLicenseResponeInner'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DrivingLicenseResponeInner'));
  } else {
    // Browser globals (root is window)
    if (!root.IimmpactApi) {
      root.IimmpactApi = {};
    }
    root.IimmpactApi.DrivingLicenseRespone = factory(root.IimmpactApi.ApiClient, root.IimmpactApi.DrivingLicenseResponeInner);
  }
}(this, function(ApiClient, DrivingLicenseResponeInner) {
  'use strict';

  /**
   * The DrivingLicenseRespone model module.
   * @module model/DrivingLicenseRespone
   * @version 2020-09-14T13:01:14Z
   */

  /**
   * Constructs a new <code>DrivingLicenseRespone</code>.
   * @alias module:model/DrivingLicenseRespone
   * @class
   * @extends Array
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DrivingLicenseRespone</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DrivingLicenseRespone} obj Optional instance to populate.
   * @return {module:model/DrivingLicenseRespone} The populated <code>DrivingLicenseRespone</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ApiClient.constructFromObject(data, obj, 'DrivingLicenseResponeInner');
    }
    return obj;
  }

  Object.setPrototypeOf(exports.prototype, new Array());
  return exports;

}));
