/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.IimmpactApi) {
      root.IimmpactApi = {};
    }
    root.IimmpactApi.DrivingTestResponeEnquiryTestPart1 = factory(root.IimmpactApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The DrivingTestResponeEnquiryTestPart1 model module.
   * @module model/DrivingTestResponeEnquiryTestPart1
   * @version 2020-09-14T13:01:14Z
   */

  /**
   * Constructs a new <code>DrivingTestResponeEnquiryTestPart1</code>.
   * @alias module:model/DrivingTestResponeEnquiryTestPart1
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DrivingTestResponeEnquiryTestPart1</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DrivingTestResponeEnquiryTestPart1} obj Optional instance to populate.
   * @return {module:model/DrivingTestResponeEnquiryTestPart1} The populated <code>DrivingTestResponeEnquiryTestPart1</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Date of Test'))
        obj.dateOfTest = ApiClient.convertToType(data['Date of Test'], 'String');
      if (data.hasOwnProperty('Test Type'))
        obj.testType = ApiClient.convertToType(data['Test Type'], 'Number');
      if (data.hasOwnProperty('License Class'))
        obj.licenseClass = ApiClient.convertToType(data['License Class'], 'Number');
      if (data.hasOwnProperty('Test Venue'))
        obj.testVenue = ApiClient.convertToType(data['Test Venue'], 'String');
      if (data.hasOwnProperty('Result'))
        obj.result = ApiClient.convertToType(data['Result'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} dateOfTest
   */
  exports.prototype.dateOfTest = undefined;

  /**
   * @member {Number} testType
   */
  exports.prototype.testType = undefined;

  /**
   * @member {Number} licenseClass
   */
  exports.prototype.licenseClass = undefined;

  /**
   * @member {String} testVenue
   */
  exports.prototype.testVenue = undefined;

  /**
   * @member {String} result
   */
  exports.prototype.result = undefined;

  return exports;

}));
