/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DrivingTestResponeEnquiryTestPart1'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DrivingTestResponeEnquiryTestPart1'));
  } else {
    // Browser globals (root is window)
    if (!root.IimmpactApi) {
      root.IimmpactApi = {};
    }
    root.IimmpactApi.DrivingTestRespone = factory(root.IimmpactApi.ApiClient, root.IimmpactApi.DrivingTestResponeEnquiryTestPart1);
  }
}(this, function(ApiClient, DrivingTestResponeEnquiryTestPart1) {
  'use strict';

  /**
   * The DrivingTestRespone model module.
   * @module model/DrivingTestRespone
   * @version 2020-09-14T13:01:14Z
   */

  /**
   * Constructs a new <code>DrivingTestRespone</code>.
   * @alias module:model/DrivingTestRespone
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DrivingTestRespone</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DrivingTestRespone} obj Optional instance to populate.
   * @return {module:model/DrivingTestRespone} The populated <code>DrivingTestRespone</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Enquiry Test Part 1'))
        obj.enquiryTestPart1 = ApiClient.convertToType(data['Enquiry Test Part 1'], [DrivingTestResponeEnquiryTestPart1]);
      if (data.hasOwnProperty('Enquiry Practical Test'))
        obj.enquiryPracticalTest = ApiClient.convertToType(data['Enquiry Practical Test'], [DrivingTestResponeEnquiryTestPart1]);
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/DrivingTestResponeEnquiryTestPart1>} enquiryTestPart1
   */
  exports.prototype.enquiryTestPart1 = undefined;

  /**
   * @member {Array.<module:model/DrivingTestResponeEnquiryTestPart1>} enquiryPracticalTest
   */
  exports.prototype.enquiryPracticalTest = undefined;

  return exports;

}));
