/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.IimmpactApi) {
      root.IimmpactApi = {};
    }
    root.IimmpactApi.InlineResponse2002Data = factory(root.IimmpactApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The InlineResponse2002Data model module.
   * @module model/InlineResponse2002Data
   * @version 2020-09-14T13:01:14Z
   */

  /**
   * Constructs a new <code>InlineResponse2002Data</code>.
   * @alias module:model/InlineResponse2002Data
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>InlineResponse2002Data</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2002Data} obj Optional instance to populate.
   * @return {module:model/InlineResponse2002Data} The populated <code>InlineResponse2002Data</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('category'))
        obj.category = ApiClient.convertToType(data['category'], 'String');
      if (data.hasOwnProperty('product_code'))
        obj.productCode = ApiClient.convertToType(data['product_code'], 'String');
      if (data.hasOwnProperty('product_name'))
        obj.productName = ApiClient.convertToType(data['product_name'], 'String');
      if (data.hasOwnProperty('denomination'))
        obj.denomination = ApiClient.convertToType(data['denomination'], 'String');
      if (data.hasOwnProperty('unit_price'))
        obj.unitPrice = ApiClient.convertToType(data['unit_price'], 'String');
      if (data.hasOwnProperty('discount'))
        obj.discount = ApiClient.convertToType(data['discount'], 'String');
      if (data.hasOwnProperty('api_parameter'))
        obj.apiParameter = ApiClient.convertToType(data['api_parameter'], 'String');
      if (data.hasOwnProperty('update_time'))
        obj.updateTime = ApiClient.convertToType(data['update_time'], 'String');
      if (data.hasOwnProperty('note'))
        obj.note = ApiClient.convertToType(data['note'], 'String');
      if (data.hasOwnProperty('product_img'))
        obj.productImg = ApiClient.convertToType(data['product_img'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} status
   */
  exports.prototype.status = undefined;

  /**
   * @member {String} category
   */
  exports.prototype.category = undefined;

  /**
   * @member {String} productCode
   */
  exports.prototype.productCode = undefined;

  /**
   * @member {String} productName
   */
  exports.prototype.productName = undefined;

  /**
   * @member {String} denomination
   */
  exports.prototype.denomination = undefined;

  /**
   * @member {String} unitPrice
   */
  exports.prototype.unitPrice = undefined;

  /**
   * @member {String} discount
   */
  exports.prototype.discount = undefined;

  /**
   * @member {String} apiParameter
   */
  exports.prototype.apiParameter = undefined;

  /**
   * @member {String} updateTime
   */
  exports.prototype.updateTime = undefined;

  /**
   * @member {String} note
   */
  exports.prototype.note = undefined;

  /**
   * @member {String} productImg
   */
  exports.prototype.productImg = undefined;

  return exports;

}));
