/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.IimmpactApi) {
      root.IimmpactApi = {};
    }
    root.IimmpactApi.JPJSummonsResponse = factory(root.IimmpactApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The JPJSummonsResponse model module.
   * @module model/JPJSummonsResponse
   * @version 2020-09-14T13:01:14Z
   */

  /**
   * Constructs a new <code>JPJSummonsResponse</code>.
   * @alias module:model/JPJSummonsResponse
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>JPJSummonsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/JPJSummonsResponse} obj Optional instance to populate.
   * @return {module:model/JPJSummonsResponse} The populated <code>JPJSummonsResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Summon Notice No.'))
        obj.summonNoticeNo_ = ApiClient.convertToType(data['Summon Notice No.'], 'String');
      if (data.hasOwnProperty('Notice Type'))
        obj.noticeType = ApiClient.convertToType(data['Notice Type'], 'String');
      if (data.hasOwnProperty('Vehicle Registration No.'))
        obj.vehicleRegistrationNo_ = ApiClient.convertToType(data['Vehicle Registration No.'], 'String');
      if (data.hasOwnProperty('Date & Time of Offenses'))
        obj.dateTimeOfOffenses = ApiClient.convertToType(data['Date & Time of Offenses'], 'String');
      if (data.hasOwnProperty('Notice Compound Payment Date'))
        obj.noticeCompoundPaymentDate = ApiClient.convertToType(data['Notice Compound Payment Date'], 'String');
      if (data.hasOwnProperty('Offenses Type'))
        obj.offensesType = ApiClient.convertToType(data['Offenses Type'], 'String');
      if (data.hasOwnProperty('Offenses Location'))
        obj.offensesLocation = ApiClient.convertToType(data['Offenses Location'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} summonNoticeNo_
   */
  exports.prototype.summonNoticeNo_ = undefined;

  /**
   * @member {String} noticeType
   */
  exports.prototype.noticeType = undefined;

  /**
   * @member {String} vehicleRegistrationNo_
   */
  exports.prototype.vehicleRegistrationNo_ = undefined;

  /**
   * @member {String} dateTimeOfOffenses
   */
  exports.prototype.dateTimeOfOffenses = undefined;

  /**
   * @member {String} noticeCompoundPaymentDate
   */
  exports.prototype.noticeCompoundPaymentDate = undefined;

  /**
   * @member {String} offensesType
   */
  exports.prototype.offensesType = undefined;

  /**
   * @member {String} offensesLocation
   */
  exports.prototype.offensesLocation = undefined;

  return exports;

}));
