/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.IimmpactApi) {
      root.IimmpactApi = {};
    }
    root.IimmpactApi.LowBalanceWarningResponseData = factory(root.IimmpactApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The LowBalanceWarningResponseData model module.
   * @module model/LowBalanceWarningResponseData
   * @version 2020-09-14T13:01:14Z
   */

  /**
   * Constructs a new <code>LowBalanceWarningResponseData</code>.
   * @alias module:model/LowBalanceWarningResponseData
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>LowBalanceWarningResponseData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LowBalanceWarningResponseData} obj Optional instance to populate.
   * @return {module:model/LowBalanceWarningResponseData} The populated <code>LowBalanceWarningResponseData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Status'))
        obj.status = ApiClient.convertToType(data['Status'], 'String');
      if (data.hasOwnProperty('Email'))
        obj.email = ApiClient.convertToType(data['Email'], 'String');
      if (data.hasOwnProperty('BalanceThreshold'))
        obj.balanceThreshold = ApiClient.convertToType(data['BalanceThreshold'], 'String');
      if (data.hasOwnProperty('Note'))
        obj.note = ApiClient.convertToType(data['Note'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} status
   */
  exports.prototype.status = undefined;

  /**
   * @member {String} email
   */
  exports.prototype.email = undefined;

  /**
   * @member {String} balanceThreshold
   */
  exports.prototype.balanceThreshold = undefined;

  /**
   * @member {String} note
   */
  exports.prototype.note = undefined;

  return exports;

}));
