/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.IimmpactApi) {
      root.IimmpactApi = {};
    }
    root.IimmpactApi.NetworkStatusResponseData = factory(root.IimmpactApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The NetworkStatusResponseData model module.
   * @module model/NetworkStatusResponseData
   * @version 2020-09-14T13:01:14Z
   */

  /**
   * Constructs a new <code>NetworkStatusResponseData</code>.
   * @alias module:model/NetworkStatusResponseData
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>NetworkStatusResponseData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NetworkStatusResponseData} obj Optional instance to populate.
   * @return {module:model/NetworkStatusResponseData} The populated <code>NetworkStatusResponseData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('product_code'))
        obj.productCode = ApiClient.convertToType(data['product_code'], 'String');
      if (data.hasOwnProperty('product_name'))
        obj.productName = ApiClient.convertToType(data['product_name'], 'String');
      if (data.hasOwnProperty('product_img'))
        obj.productImg = ApiClient.convertToType(data['product_img'], 'String');
      if (data.hasOwnProperty('network_status'))
        obj.networkStatus = ApiClient.convertToType(data['network_status'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} productCode
   */
  exports.prototype.productCode = undefined;

  /**
   * @member {String} productName
   */
  exports.prototype.productName = undefined;

  /**
   * @member {String} productImg
   */
  exports.prototype.productImg = undefined;

  /**
   * @member {String} networkStatus
   */
  exports.prototype.networkStatus = undefined;

  return exports;

}));
