/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.IimmpactApi) {
      root.IimmpactApi = {};
    }
    root.IimmpactApi.NewPasswordRequest = factory(root.IimmpactApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The NewPasswordRequest model module.
   * @module model/NewPasswordRequest
   * @version 2020-09-14T13:01:14Z
   */

  /**
   * Constructs a new <code>NewPasswordRequest</code>.
   * @alias module:model/NewPasswordRequest
   * @class
   */
  var exports = function(username, old_password, new_password, session) {
    this.username = username;
    this.old_password = old_password;
    this.new_password = new_password;
    this.session = session;
  };

  /**
   * Constructs a <code>NewPasswordRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NewPasswordRequest} obj Optional instance to populate.
   * @return {module:model/NewPasswordRequest} The populated <code>NewPasswordRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('old_password'))
        obj.oldPassword = ApiClient.convertToType(data['old_password'], 'String');
      if (data.hasOwnProperty('new_password'))
        obj.newPassword = ApiClient.convertToType(data['new_password'], 'String');
      if (data.hasOwnProperty('session'))
        obj.session = ApiClient.convertToType(data['session'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} username
   */
  exports.prototype.username = undefined;

  /**
   * @member {String} oldPassword
   */
  exports.prototype.oldPassword = undefined;

  /**
   * @member {String} newPassword
   */
  exports.prototype.newPassword = undefined;

  /**
   * @member {String} session
   */
  exports.prototype.session = undefined;

  return exports;

}));
