/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.IimmpactApi) {
      root.IimmpactApi = {};
    }
    root.IimmpactApi.OnlyMessageRespone = factory(root.IimmpactApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The OnlyMessageRespone model module.
   * @module model/OnlyMessageRespone
   * @version 2020-09-14T13:01:14Z
   */

  /**
   * Constructs a new <code>OnlyMessageRespone</code>.
   * @alias module:model/OnlyMessageRespone
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>OnlyMessageRespone</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OnlyMessageRespone} obj Optional instance to populate.
   * @return {module:model/OnlyMessageRespone} The populated <code>OnlyMessageRespone</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], 'String');
      if (data.hasOwnProperty('content-type'))
        obj.contentType = ApiClient.convertToType(data['content-type'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} message
   */
  exports.prototype.message = undefined;

  /**
   * @member {String} data
   */
  exports.prototype.data = undefined;

  /**
   * @member {String} contentType
   */
  exports.prototype.contentType = undefined;

  return exports;

}));
