/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.IimmpactApi) {
      root.IimmpactApi = {};
    }
    root.IimmpactApi.TokenResponseAuthenticationResult = factory(root.IimmpactApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The TokenResponseAuthenticationResult model module.
   * @module model/TokenResponseAuthenticationResult
   * @version 2020-09-14T13:01:14Z
   */

  /**
   * Constructs a new <code>TokenResponseAuthenticationResult</code>.
   * @alias module:model/TokenResponseAuthenticationResult
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>TokenResponseAuthenticationResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TokenResponseAuthenticationResult} obj Optional instance to populate.
   * @return {module:model/TokenResponseAuthenticationResult} The populated <code>TokenResponseAuthenticationResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('AccessToken'))
        obj.accessToken = ApiClient.convertToType(data['AccessToken'], 'String');
      if (data.hasOwnProperty('ExpiresIn'))
        obj.expiresIn = ApiClient.convertToType(data['ExpiresIn'], 'Number');
      if (data.hasOwnProperty('TokenType'))
        obj.tokenType = ApiClient.convertToType(data['TokenType'], 'String');
      if (data.hasOwnProperty('RefreshToken'))
        obj.refreshToken = ApiClient.convertToType(data['RefreshToken'], 'String');
      if (data.hasOwnProperty('IdToken'))
        obj.idToken = ApiClient.convertToType(data['IdToken'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} accessToken
   */
  exports.prototype.accessToken = undefined;

  /**
   * @member {Number} expiresIn
   */
  exports.prototype.expiresIn = undefined;

  /**
   * @member {String} tokenType
   */
  exports.prototype.tokenType = undefined;

  /**
   * @member {String} refreshToken
   */
  exports.prototype.refreshToken = undefined;

  /**
   * @member {String} idToken
   */
  exports.prototype.idToken = undefined;

  return exports;

}));
