/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.IimmpactApi) {
      root.IimmpactApi = {};
    }
    root.IimmpactApi.TopupRequest = factory(root.IimmpactApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The TopupRequest model module.
   * @module model/TopupRequest
   * @version 2020-09-14T13:01:14Z
   */

  /**
   * Constructs a new <code>TopupRequest</code>.
   * @alias module:model/TopupRequest
   * @class
   * @param refid {String} 
   * @param product {String} 
   * @param account {String} 
   * @param amount {Number} 
   */
  var exports = function(refid, product, account, amount) {
    this.refid = refid;
    this.product = product;
    this.account = account;
    this.amount = amount;
  };

  /**
   * Constructs a <code>TopupRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TopupRequest} obj Optional instance to populate.
   * @return {module:model/TopupRequest} The populated <code>TopupRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('refid'))
        obj.refid = ApiClient.convertToType(data['refid'], 'String');
      if (data.hasOwnProperty('product'))
        obj.product = ApiClient.convertToType(data['product'], 'String');
      if (data.hasOwnProperty('remarks'))
        obj.remarks = ApiClient.convertToType(data['remarks'], 'String');
      if (data.hasOwnProperty('account'))
        obj.account = ApiClient.convertToType(data['account'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('sync'))
        obj.sync = ApiClient.convertToType(data['sync'], 'Boolean');
    }
    return obj;
  }

  /**
   * @member {String} refid
   */
  exports.prototype.refid = undefined;

  /**
   * @member {String} product
   */
  exports.prototype.product = undefined;

  /**
   * @member {String} remarks
   */
  exports.prototype.remarks = undefined;

  /**
   * @member {String} account
   */
  exports.prototype.account = undefined;

  /**
   * @member {Number} amount
   */
  exports.prototype.amount = undefined;

  /**
   * @member {Boolean} sync
   */
  exports.prototype.sync = undefined;

  return exports;

}));
