/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TopupResponseData'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TopupResponseData'));
  } else {
    // Browser globals (root is window)
    if (!root.IimmpactApi) {
      root.IimmpactApi = {};
    }
    root.IimmpactApi.TopupResponse = factory(root.IimmpactApi.ApiClient, root.IimmpactApi.TopupResponseData);
  }
}(this, function(ApiClient, TopupResponseData) {
  'use strict';

  /**
   * The TopupResponse model module.
   * @module model/TopupResponse
   * @version 2020-09-14T13:01:14Z
   */

  /**
   * Constructs a new <code>TopupResponse</code>.
   * @alias module:model/TopupResponse
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>TopupResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TopupResponse} obj Optional instance to populate.
   * @return {module:model/TopupResponse} The populated <code>TopupResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('data'))
        obj.data = TopupResponseData.constructFromObject(data['data']);
    }
    return obj;
  }

  /**
   * @member {module:model/TopupResponseData} data
   */
  exports.prototype.data = undefined;

  return exports;

}));
