/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TransactionsResponseData', 'model/TransactionsResponseMeta'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TransactionsResponseData'), require('./TransactionsResponseMeta'));
  } else {
    // Browser globals (root is window)
    if (!root.IimmpactApi) {
      root.IimmpactApi = {};
    }
    root.IimmpactApi.TransactionsResponse = factory(root.IimmpactApi.ApiClient, root.IimmpactApi.TransactionsResponseData, root.IimmpactApi.TransactionsResponseMeta);
  }
}(this, function(ApiClient, TransactionsResponseData, TransactionsResponseMeta) {
  'use strict';

  /**
   * The TransactionsResponse model module.
   * @module model/TransactionsResponse
   * @version 2020-09-14T13:01:14Z
   */

  /**
   * Constructs a new <code>TransactionsResponse</code>.
   * @alias module:model/TransactionsResponse
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>TransactionsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TransactionsResponse} obj Optional instance to populate.
   * @return {module:model/TransactionsResponse} The populated <code>TransactionsResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], [TransactionsResponseData]);
      if (data.hasOwnProperty('meta'))
        obj.meta = TransactionsResponseMeta.constructFromObject(data['meta']);
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/TransactionsResponseData>} data
   */
  exports.prototype.data = undefined;

  /**
   * @member {module:model/TransactionsResponseMeta} meta
   */
  exports.prototype.meta = undefined;

  return exports;

}));
