/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.IimmpactApi) {
      root.IimmpactApi = {};
    }
    root.IimmpactApi.VehicleExpiryResponse = factory(root.IimmpactApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The VehicleExpiryResponse model module.
   * @module model/VehicleExpiryResponse
   * @version 2020-09-14T13:01:14Z
   */

  /**
   * Constructs a new <code>VehicleExpiryResponse</code>.
   * @alias module:model/VehicleExpiryResponse
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>VehicleExpiryResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VehicleExpiryResponse} obj Optional instance to populate.
   * @return {module:model/VehicleExpiryResponse} The populated <code>VehicleExpiryResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Vehicle Plate Number'))
        obj.vehiclePlateNumber = ApiClient.convertToType(data['Vehicle Plate Number'], 'String');
      if (data.hasOwnProperty('Date of Commencement'))
        obj.dateOfCommencement = ApiClient.convertToType(data['Date of Commencement'], 'String');
      if (data.hasOwnProperty('Expiry Date'))
        obj.expiryDate = ApiClient.convertToType(data['Expiry Date'], 'String');
      if (data.hasOwnProperty('Insurance Expiry Date'))
        obj.insuranceExpiryDate = ApiClient.convertToType(data['Insurance Expiry Date'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} vehiclePlateNumber
   */
  exports.prototype.vehiclePlateNumber = undefined;

  /**
   * @member {String} dateOfCommencement
   */
  exports.prototype.dateOfCommencement = undefined;

  /**
   * @member {String} expiryDate
   */
  exports.prototype.expiryDate = undefined;

  /**
   * @member {String} insuranceExpiryDate
   */
  exports.prototype.insuranceExpiryDate = undefined;

  return exports;

}));
