/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Error', 'model/RefreshTokenRequest', 'model/TokenRequest', 'model/TokenResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Error'), require('../model/RefreshTokenRequest'), require('../model/TokenRequest'), require('../model/TokenResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.IimmpactApi) {
      root.IimmpactApi = {};
    }
    root.IimmpactApi.AuthorizationTokenApi = factory(root.IimmpactApi.ApiClient, root.IimmpactApi.Error, root.IimmpactApi.RefreshTokenRequest, root.IimmpactApi.TokenRequest, root.IimmpactApi.TokenResponse);
  }
}(this, function(ApiClient, Error, RefreshTokenRequest, TokenRequest, TokenResponse) {
  'use strict';

  /**
   * AuthorizationToken service.
   * @module api/AuthorizationTokenApi
   * @version 2020-09-14T13:01:14Z
   */

  /**
   * Constructs a new AuthorizationTokenApi. 
   * @alias module:api/AuthorizationTokenApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the v1TokenPost operation.
     * @callback module:api/AuthorizationTokenApi~v1TokenPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TokenResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/TokenRequest} tokenRequest 
     * @param {module:api/AuthorizationTokenApi~v1TokenPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TokenResponse}
     */
    this.v1TokenPost = function(tokenRequest, callback) {
      var postBody = tokenRequest;

      // verify the required parameter 'tokenRequest' is set
      if (tokenRequest === undefined || tokenRequest === null) {
        throw new Error("Missing the required parameter 'tokenRequest' when calling v1TokenPost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = TokenResponse;

      return this.apiClient.callApi(
        '/v1/token', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the v1TokenRefreshPost operation.
     * @callback module:api/AuthorizationTokenApi~v1TokenRefreshPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TokenResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/RefreshTokenRequest} refreshTokenRequest 
     * @param {module:api/AuthorizationTokenApi~v1TokenRefreshPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TokenResponse}
     */
    this.v1TokenRefreshPost = function(refreshTokenRequest, callback) {
      var postBody = refreshTokenRequest;

      // verify the required parameter 'refreshTokenRequest' is set
      if (refreshTokenRequest === undefined || refreshTokenRequest === null) {
        throw new Error("Missing the required parameter 'refreshTokenRequest' when calling v1TokenRefreshPost");
      }

      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = TokenResponse;

      return this.apiClient.callApi(
        '/v1/token/refresh', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
