/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CallbackUrlResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/CallbackUrlResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.IimmpactApi) {
      root.IimmpactApi = {};
    }
    root.IimmpactApi.CallbackUrlApi = factory(root.IimmpactApi.ApiClient, root.IimmpactApi.CallbackUrlResponse);
  }
}(this, function(ApiClient, CallbackUrlResponse) {
  'use strict';

  /**
   * CallbackUrl service.
   * @module api/CallbackUrlApi
   * @version 2020-09-14T13:01:14Z
   */

  /**
   * Constructs a new CallbackUrlApi. 
   * @alias module:api/CallbackUrlApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the v1CallbackUrlGet operation.
     * @callback module:api/CallbackUrlApi~v1CallbackUrlGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CallbackUrlResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/CallbackUrlApi~v1CallbackUrlGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CallbackUrlResponse}
     */
    this.v1CallbackUrlGet = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['SSO'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = CallbackUrlResponse;

      return this.apiClient.callApi(
        '/v1/callback-url', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the v1CallbackUrlPost operation.
     * @callback module:api/CallbackUrlApi~v1CallbackUrlPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CallbackUrlResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} url 
     * @param {module:api/CallbackUrlApi~v1CallbackUrlPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CallbackUrlResponse}
     */
    this.v1CallbackUrlPost = function(url, callback) {
      var postBody = null;

      // verify the required parameter 'url' is set
      if (url === undefined || url === null) {
        throw new Error("Missing the required parameter 'url' when calling v1CallbackUrlPost");
      }


      var pathParams = {
      };
      var queryParams = {
        'url': url,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['SSO'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = CallbackUrlResponse;

      return this.apiClient.callApi(
        '/v1/callback-url', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
