/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/LowBalanceWarningResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/LowBalanceWarningResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.IimmpactApi) {
      root.IimmpactApi = {};
    }
    root.IimmpactApi.LowBalanceWarningApi = factory(root.IimmpactApi.ApiClient, root.IimmpactApi.LowBalanceWarningResponse);
  }
}(this, function(ApiClient, LowBalanceWarningResponse) {
  'use strict';

  /**
   * LowBalanceWarning service.
   * @module api/LowBalanceWarningApi
   * @version 2020-09-14T13:01:14Z
   */

  /**
   * Constructs a new LowBalanceWarningApi. 
   * @alias module:api/LowBalanceWarningApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the v1LowBalanceThresholdGet operation.
     * @callback module:api/LowBalanceWarningApi~v1LowBalanceThresholdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LowBalanceWarningResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/LowBalanceWarningApi~v1LowBalanceThresholdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LowBalanceWarningResponse}
     */
    this.v1LowBalanceThresholdGet = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['SSO'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = LowBalanceWarningResponse;

      return this.apiClient.callApi(
        '/v1/low-balance-threshold', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the v1LowBalanceThresholdPost operation.
     * @callback module:api/LowBalanceWarningApi~v1LowBalanceThresholdPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LowBalanceWarningResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} amount 
     * @param {module:api/LowBalanceWarningApi~v1LowBalanceThresholdPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LowBalanceWarningResponse}
     */
    this.v1LowBalanceThresholdPost = function(amount, callback) {
      var postBody = null;

      // verify the required parameter 'amount' is set
      if (amount === undefined || amount === null) {
        throw new Error("Missing the required parameter 'amount' when calling v1LowBalanceThresholdPost");
      }


      var pathParams = {
      };
      var queryParams = {
        'amount': amount,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['SSO'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = LowBalanceWarningResponse;

      return this.apiClient.callApi(
        '/v1/low-balance-threshold', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
