/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IimmpactApi);
  }
}(this, function(expect, IimmpactApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('BillPresentmentResponseData', function() {
      beforeEach(function() {
        instance = new IimmpactApi.BillPresentmentResponseData();
      });

      it('should create an instance of BillPresentmentResponseData', function() {
        // TODO: update the code to test BillPresentmentResponseData
        expect(instance).to.be.a(IimmpactApi.BillPresentmentResponseData);
      });

      it('should have the property message (base name: "message")', function() {
        // TODO: update the code to test the property message
        expect(instance).to.have.property('message');
        // expect(instance.message).to.be(expectedValueLiteral);
      });

      it('should have the property customField (base name: "CustomField")', function() {
        // TODO: update the code to test the property customField
        expect(instance).to.have.property('customField');
        // expect(instance.customField).to.be(expectedValueLiteral);
      });

      it('should have the property customerName (base name: "CustomerName")', function() {
        // TODO: update the code to test the property customerName
        expect(instance).to.have.property('customerName');
        // expect(instance.customerName).to.be(expectedValueLiteral);
      });

      it('should have the property outstanding (base name: "Outstanding")', function() {
        // TODO: update the code to test the property outstanding
        expect(instance).to.have.property('outstanding');
        // expect(instance.outstanding).to.be(expectedValueLiteral);
      });

      it('should have the property balance (base name: "Balance")', function() {
        // TODO: update the code to test the property balance
        expect(instance).to.have.property('balance');
        // expect(instance.balance).to.be(expectedValueLiteral);
      });

      it('should have the property data (base name: "Data")', function() {
        // TODO: update the code to test the property data
        expect(instance).to.have.property('data');
        // expect(instance.data).to.be(expectedValueLiteral);
      });

      it('should have the property address (base name: "Address")', function() {
        // TODO: update the code to test the property address
        expect(instance).to.have.property('address');
        // expect(instance.address).to.be(expectedValueLiteral);
      });

      it('should have the property eBill (base name: "E-Bill")', function() {
        // TODO: update the code to test the property eBill
        expect(instance).to.have.property('eBill');
        // expect(instance.eBill).to.be(expectedValueLiteral);
      });

    });
  });

}));
