/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IimmpactApi);
  }
}(this, function(expect, IimmpactApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CallbackUrlResponseData', function() {
      beforeEach(function() {
        instance = new IimmpactApi.CallbackUrlResponseData();
      });

      it('should create an instance of CallbackUrlResponseData', function() {
        // TODO: update the code to test CallbackUrlResponseData
        expect(instance).to.be.a(IimmpactApi.CallbackUrlResponseData);
      });

      it('should have the property status (base name: "Status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property callbackUrl (base name: "CallbackUrl")', function() {
        // TODO: update the code to test the property callbackUrl
        expect(instance).to.have.property('callbackUrl');
        // expect(instance.callbackUrl).to.be(expectedValueLiteral);
      });

    });
  });

}));
