/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IimmpactApi);
  }
}(this, function(expect, IimmpactApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DrivingTestResponeEnquiryTestPart1', function() {
      beforeEach(function() {
        instance = new IimmpactApi.DrivingTestResponeEnquiryTestPart1();
      });

      it('should create an instance of DrivingTestResponeEnquiryTestPart1', function() {
        // TODO: update the code to test DrivingTestResponeEnquiryTestPart1
        expect(instance).to.be.a(IimmpactApi.DrivingTestResponeEnquiryTestPart1);
      });

      it('should have the property dateOfTest (base name: "Date of Test")', function() {
        // TODO: update the code to test the property dateOfTest
        expect(instance).to.have.property('dateOfTest');
        // expect(instance.dateOfTest).to.be(expectedValueLiteral);
      });

      it('should have the property testType (base name: "Test Type")', function() {
        // TODO: update the code to test the property testType
        expect(instance).to.have.property('testType');
        // expect(instance.testType).to.be(expectedValueLiteral);
      });

      it('should have the property licenseClass (base name: "License Class")', function() {
        // TODO: update the code to test the property licenseClass
        expect(instance).to.have.property('licenseClass');
        // expect(instance.licenseClass).to.be(expectedValueLiteral);
      });

      it('should have the property testVenue (base name: "Test Venue")', function() {
        // TODO: update the code to test the property testVenue
        expect(instance).to.have.property('testVenue');
        // expect(instance.testVenue).to.be(expectedValueLiteral);
      });

      it('should have the property result (base name: "Result")', function() {
        // TODO: update the code to test the property result
        expect(instance).to.have.property('result');
        // expect(instance.result).to.be(expectedValueLiteral);
      });

    });
  });

}));
