/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IimmpactApi);
  }
}(this, function(expect, IimmpactApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TransactionsResponseMeta', function() {
      beforeEach(function() {
        instance = new IimmpactApi.TransactionsResponseMeta();
      });

      it('should create an instance of TransactionsResponseMeta', function() {
        // TODO: update the code to test TransactionsResponseMeta
        expect(instance).to.be.a(IimmpactApi.TransactionsResponseMeta);
      });

      it('should have the property totalAmount (base name: "total_amount")', function() {
        // TODO: update the code to test the property totalAmount
        expect(instance).to.have.property('totalAmount');
        // expect(instance.totalAmount).to.be(expectedValueLiteral);
      });

      it('should have the property totalPrice (base name: "total_price")', function() {
        // TODO: update the code to test the property totalPrice
        expect(instance).to.have.property('totalPrice');
        // expect(instance.totalPrice).to.be(expectedValueLiteral);
      });

      it('should have the property transactionCount (base name: "transaction_count")', function() {
        // TODO: update the code to test the property transactionCount
        expect(instance).to.have.property('transactionCount');
        // expect(instance.transactionCount).to.be(expectedValueLiteral);
      });

    });
  });

}));
