/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IimmpactApi);
  }
}(this, function(expect, IimmpactApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TransactionsResponseData', function() {
      beforeEach(function() {
        instance = new IimmpactApi.TransactionsResponseData();
      });

      it('should create an instance of TransactionsResponseData', function() {
        // TODO: update the code to test TransactionsResponseData
        expect(instance).to.be.a(IimmpactApi.TransactionsResponseData);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property entryDate (base name: "entry_date")', function() {
        // TODO: update the code to test the property entryDate
        expect(instance).to.have.property('entryDate');
        // expect(instance.entryDate).to.be(expectedValueLiteral);
      });

      it('should have the property product (base name: "product")', function() {
        // TODO: update the code to test the property product
        expect(instance).to.have.property('product');
        // expect(instance.product).to.be(expectedValueLiteral);
      });

      it('should have the property amount (base name: "amount")', function() {
        // TODO: update the code to test the property amount
        expect(instance).to.have.property('amount');
        // expect(instance.amount).to.be(expectedValueLiteral);
      });

      it('should have the property topupNumber (base name: "topup_number")', function() {
        // TODO: update the code to test the property topupNumber
        expect(instance).to.have.property('topupNumber');
        // expect(instance.topupNumber).to.be(expectedValueLiteral);
      });

      it('should have the property sender (base name: "sender")', function() {
        // TODO: update the code to test the property sender
        expect(instance).to.have.property('sender');
        // expect(instance.sender).to.be(expectedValueLiteral);
      });

      it('should have the property memberId (base name: "member_id")', function() {
        // TODO: update the code to test the property memberId
        expect(instance).to.have.property('memberId');
        // expect(instance.memberId).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property balance (base name: "balance")', function() {
        // TODO: update the code to test the property balance
        expect(instance).to.have.property('balance');
        // expect(instance.balance).to.be(expectedValueLiteral);
      });

      it('should have the property price (base name: "price")', function() {
        // TODO: update the code to test the property price
        expect(instance).to.have.property('price');
        // expect(instance.price).to.be(expectedValueLiteral);
      });

      it('should have the property sn (base name: "sn")', function() {
        // TODO: update the code to test the property sn
        expect(instance).to.have.property('sn');
        // expect(instance.sn).to.be(expectedValueLiteral);
      });

      it('should have the property remarks (base name: "remarks")', function() {
        // TODO: update the code to test the property remarks
        expect(instance).to.have.property('remarks');
        // expect(instance.remarks).to.be(expectedValueLiteral);
      });

      it('should have the property refId (base name: "ref_id")', function() {
        // TODO: update the code to test the property refId
        expect(instance).to.have.property('refId');
        // expect(instance.refId).to.be(expectedValueLiteral);
      });

    });
  });

}));
