/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IimmpactApi);
  }
}(this, function(expect, IimmpactApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('VehicleExpiryResponse', function() {
      beforeEach(function() {
        instance = new IimmpactApi.VehicleExpiryResponse();
      });

      it('should create an instance of VehicleExpiryResponse', function() {
        // TODO: update the code to test VehicleExpiryResponse
        expect(instance).to.be.a(IimmpactApi.VehicleExpiryResponse);
      });

      it('should have the property vehiclePlateNumber (base name: "Vehicle Plate Number")', function() {
        // TODO: update the code to test the property vehiclePlateNumber
        expect(instance).to.have.property('vehiclePlateNumber');
        // expect(instance.vehiclePlateNumber).to.be(expectedValueLiteral);
      });

      it('should have the property dateOfCommencement (base name: "Date of Commencement")', function() {
        // TODO: update the code to test the property dateOfCommencement
        expect(instance).to.have.property('dateOfCommencement');
        // expect(instance.dateOfCommencement).to.be(expectedValueLiteral);
      });

      it('should have the property expiryDate (base name: "Expiry Date")', function() {
        // TODO: update the code to test the property expiryDate
        expect(instance).to.have.property('expiryDate');
        // expect(instance.expiryDate).to.be(expectedValueLiteral);
      });

      it('should have the property insuranceExpiryDate (base name: "Insurance Expiry Date")', function() {
        // TODO: update the code to test the property insuranceExpiryDate
        expect(instance).to.have.property('insuranceExpiryDate');
        // expect(instance.insuranceExpiryDate).to.be(expectedValueLiteral);
      });

    });
  });

}));
