/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IimmpactApi);
  }
}(this, function(expect, IimmpactApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IimmpactApi.AuthorizationTokenApi();
  });

  describe('(package)', function() {
    describe('AuthorizationTokenApi', function() {
      describe('v1TokenPost', function() {
        it('should call v1TokenPost successfully', function(done) {
          // TODO: uncomment, update parameter values for v1TokenPost call and complete the assertions
          /*
          var tokenRequest = new IimmpactApi.TokenRequest();
          tokenRequest.username = "";
          tokenRequest.password = "";

          instance.v1TokenPost(tokenRequest, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IimmpactApi.TokenResponse);
            expect(data.authenticationResult).to.be.a(IimmpactApi.TokenResponseAuthenticationResult);
                  expect(data.authenticationResult.accessToken).to.be.a('string');
              expect(data.authenticationResult.accessToken).to.be("");
              expect(data.authenticationResult.expiresIn).to.be.a('number');
              expect(data.authenticationResult.expiresIn).to.be(0);
              expect(data.authenticationResult.tokenType).to.be.a('string');
              expect(data.authenticationResult.tokenType).to.be("");
              expect(data.authenticationResult.refreshToken).to.be.a('string');
              expect(data.authenticationResult.refreshToken).to.be("");
              expect(data.authenticationResult.idToken).to.be.a('string');
              expect(data.authenticationResult.idToken).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('v1TokenRefreshPost', function() {
        it('should call v1TokenRefreshPost successfully', function(done) {
          // TODO: uncomment, update parameter values for v1TokenRefreshPost call and complete the assertions
          /*
          var refreshTokenRequest = new IimmpactApi.RefreshTokenRequest();
          refreshTokenRequest.refreshToken = "";

          instance.v1TokenRefreshPost(refreshTokenRequest, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IimmpactApi.TokenResponse);
            expect(data.authenticationResult).to.be.a(IimmpactApi.TokenResponseAuthenticationResult);
                  expect(data.authenticationResult.accessToken).to.be.a('string');
              expect(data.authenticationResult.accessToken).to.be("");
              expect(data.authenticationResult.expiresIn).to.be.a('number');
              expect(data.authenticationResult.expiresIn).to.be(0);
              expect(data.authenticationResult.tokenType).to.be.a('string');
              expect(data.authenticationResult.tokenType).to.be("");
              expect(data.authenticationResult.refresh_token).to.be.a('string');
              expect(data.authenticationResult.refresh_token).to.be("");
              expect(data.authenticationResult.idToken).to.be.a('string');
              expect(data.authenticationResult.idToken).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
