/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IimmpactApi);
  }
}(this, function(expect, IimmpactApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IimmpactApi.CallbackUrlApi();
  });

  describe('(package)', function() {
    describe('CallbackUrlApi', function() {
      describe('v1CallbackUrlGet', function() {
        it('should call v1CallbackUrlGet successfully', function(done) {
          // TODO: uncomment v1CallbackUrlGet call and complete the assertions
          /*

          instance.v1CallbackUrlGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IimmpactApi.CallbackUrlResponse);
            expect(data.data).to.be.a(IimmpactApi.CallbackUrlResponseData);
                  expect(data.data.status).to.be.a('string');
              expect(data.data.status).to.be("");
              expect(data.data.callbackUrl).to.be.a('string');
              expect(data.data.callbackUrl).to.be("");
            expect(data.metadata).to.be.a(IimmpactApi.CallbackUrlResponseMetadata);
                  expect(data.metadata.statusCode).to.be.a('number');
              expect(data.metadata.statusCode).to.be();
              expect(data.metadata.lastUpdated).to.be.a('string');
              expect(data.metadata.lastUpdated).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('v1CallbackUrlPost', function() {
        it('should call v1CallbackUrlPost successfully', function(done) {
          // TODO: uncomment, update parameter values for v1CallbackUrlPost call and complete the assertions
          /*
          var url = "url_example";

          instance.v1CallbackUrlPost(url, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IimmpactApi.CallbackUrlResponse);
            expect(data.data).to.be.a(IimmpactApi.CallbackUrlResponseData);
                  expect(data.data.status).to.be.a('string');
              expect(data.data.status).to.be("");
              expect(data.data.callbackUrl).to.be.a('string');
              expect(data.data.callbackUrl).to.be("");
            expect(data.metadata).to.be.a(IimmpactApi.CallbackUrlResponseMetadata);
                  expect(data.metadata.statusCode).to.be.a('number');
              expect(data.metadata.statusCode).to.be();
              expect(data.metadata.lastUpdated).to.be.a('string');
              expect(data.metadata.lastUpdated).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
