/*
 * IIMMPACT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IimmpactApi);
  }
}(this, function(expect, IimmpactApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IimmpactApi.JPJRecordsApi();
  });

  describe('(package)', function() {
    describe('JPJRecordsApi', function() {
      describe('v1JpjDrivingLicenseGet', function() {
        it('should call v1JpjDrivingLicenseGet successfully', function(done) {
          // TODO: uncomment, update parameter values for v1JpjDrivingLicenseGet call and complete the assertions
          /*
          var idNo = "idNo_example";
          var idType = "idType_example";
          var opts = {};
          opts.captcha = "captcha_example";

          instance.v1JpjDrivingLicenseGet(idNo, idType, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IimmpactApi.DrivingLicenseRespone);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('v1JpjDrivingTestResultsGet', function() {
        it('should call v1JpjDrivingTestResultsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for v1JpjDrivingTestResultsGet call and complete the assertions
          /*
          var idNo = "idNo_example";
          var idType = "idType_example";
          var opts = {};
          opts.captcha = "captcha_example";

          instance.v1JpjDrivingTestResultsGet(idNo, idType, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IimmpactApi.DrivingTestRespone);
            {
              let dataCtr = data.enquiryTestPart1;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(IimmpactApi.DrivingTestResponeEnquiryTestPart1);
                expect(data.dateOfTest).to.be.a('string');
                expect(data.dateOfTest).to.be("");
                expect(data.testType).to.be.a('number');
                expect(data.testType).to.be();
                expect(data.licenseClass).to.be.a('number');
                expect(data.licenseClass).to.be();
                expect(data.testVenue).to.be.a('string');
                expect(data.testVenue).to.be("");
                expect(data.result).to.be.a('string');
                expect(data.result).to.be("");

                      }
            }
            {
              let dataCtr = data.enquiryPracticalTest;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(IimmpactApi.DrivingTestResponeEnquiryTestPart1);
                expect(data.dateOfTest).to.be.a('string');
                expect(data.dateOfTest).to.be("");
                expect(data.testType).to.be.a('number');
                expect(data.testType).to.be();
                expect(data.licenseClass).to.be.a('number');
                expect(data.licenseClass).to.be();
                expect(data.testVenue).to.be.a('string');
                expect(data.testVenue).to.be("");
                expect(data.result).to.be.a('string');
                expect(data.result).to.be("");

                      }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('v1JpjMotorVehicleExpiryGet', function() {
        it('should call v1JpjMotorVehicleExpiryGet successfully', function(done) {
          // TODO: uncomment, update parameter values for v1JpjMotorVehicleExpiryGet call and complete the assertions
          /*
          var idNo = "idNo_example";
          var idType = "idType_example";
          var vehicleNo = "vehicleNo_example";
          var opts = {};
          opts.captcha = "captcha_example";

          instance.v1JpjMotorVehicleExpiryGet(idNo, idType, vehicleNo, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IimmpactApi.VehicleExpiryResponse);
            expect(data.vehiclePlateNumber).to.be.a('string');
            expect(data.vehiclePlateNumber).to.be("");
            expect(data.dateOfCommencement).to.be.a('string');
            expect(data.dateOfCommencement).to.be("");
            expect(data.expiryDate).to.be.a('string');
            expect(data.expiryDate).to.be("");
            expect(data.insuranceExpiryDate).to.be.a('string');
            expect(data.insuranceExpiryDate).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('v1JpjSummonsGet', function() {
        it('should call v1JpjSummonsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for v1JpjSummonsGet call and complete the assertions
          /*
          var idNo = "idNo_example";
          var idType = "idType_example";
          var opts = {};
          opts.captcha = "captcha_example";

          instance.v1JpjSummonsGet(idNo, idType, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IimmpactApi.JPJSummonsResponse);
            expect(data.summonNoticeNo_).to.be.a('string');
            expect(data.summonNoticeNo_).to.be("");
            expect(data.noticeType).to.be.a('string');
            expect(data.noticeType).to.be("");
            expect(data.vehicleRegistrationNo_).to.be.a('string');
            expect(data.vehicleRegistrationNo_).to.be("");
            expect(data.dateTimeOfOffenses).to.be.a('string');
            expect(data.dateTimeOfOffenses).to.be("");
            expect(data.noticeCompoundPaymentDate).to.be.a('string');
            expect(data.noticeCompoundPaymentDate).to.be("");
            expect(data.offensesType).to.be.a('string');
            expect(data.offensesType).to.be("");
            expect(data.offensesLocation).to.be.a('string');
            expect(data.offensesLocation).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
